[package]
name = "editorconfiger"
version = "0.1.3"
description = "Plain tool to validate and compare .editorconfig files"
authors = ["egoroff <egoroff@gmail.com>"]
keywords = ["editorconfig"]
homepage = "https://github.com/aegoroff/editorconfiger"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19"

[dependencies]
lalrpop-util  = { version = "0.19", features = ["lexer"] }
regex = "1"
clap = "2"
ansi_term = "0.12"
prettytable-rs = "^0.8"
jwalk = "0.6"
aho-corasick = "0.7"
nom = "7"
num_cpus = "1.13.0"

[dev-dependencies]
table-test = "0.2.1"
spectral = "0.6.0"

[[bin]]
name = "editorconfig"

[profile.release]
lto = true
