[package]
name = "editorconfiger"
version = "0.3.0"
description = "Plain tool to validate and compare .editorconfig files"
authors = ["egoroff <egoroff@gmail.com>"]
keywords = ["editorconfig"]
homepage = "https://github.com/aegoroff/editorconfiger"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19"

[dependencies]
lalrpop-util  = { version = "0.19", features = ["lexer"] }
regex = "1"
jwalk = "0.6"
aho-corasick = "0.7"
nom = "7"
num_cpus = "1.13.1"

ansi_term = { version = "0.12", optional = true }
prettytable-rs = { version = "^0.9", optional = true }
clap = { version = "4.0.11", features = ["std", "color", "suggestions", "cargo"], optional = true }

[dev-dependencies]
table-test = "0.2.1"
rstest = "0.15.0"

[features]
build-binary = ["clap", "ansi_term", "prettytable-rs"]

[[bin]]
name = "editorconfiger"
required-features = ["build-binary"]

[profile.release]
lto = true
strip = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/x86_64-unknown-linux-musl/release/editorconfiger", dest = "/usr/bin/editorconfiger", mode = "0755" },
]
